//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 0168
#pragma warning disable 0108
using System;
using System.Linq;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;
using Acme.TestProject.EFDAL.Entity;

namespace Acme.TestProject.EFDAL
{
	#region Entity Context

	/// <summary />
	[System.CodeDom.Compiler.GeneratedCode("nHydrate", "7.0.0")]
	public partial interface ITestProjectEntities : System.IDisposable
	{
		/// <summary />
		int SaveChanges();

		/// <summary />
		IQueryable<Acme.TestProject.EFDAL.Entity.Customer> Customer { get ; }

		/// <summary />
		IQueryable<Acme.TestProject.EFDAL.Entity.Order> Order { get ; }

		/// <summary />
		Acme.TestProject.EFDAL.IBusinessObject AddItem(Acme.TestProject.EFDAL.IBusinessObject entity);

		/// <summary />
		void RemoveItem(Acme.TestProject.EFDAL.IBusinessObject entity);

		/// <summary />
		void ReloadItem(BaseEntity entity);

		/// <summary />
		ContextStartup ContextStartup { get; }

		/// <summary />
		System.Guid InstanceKey { get; }
	}

	#endregion

}

#pragma warning restore 0168
#pragma warning restore 0108
